### ISSUE TITLE
No .apphub example in readme

### ISSUE THREAD

**Issue by richardgill** [joshuapinter/apphubdeploy#1]
I had to dig through source code to find it.

**Comment by joshuapinter** [comment]
Good call.

The apphubdeploy will ask for your AppHub.io credentials on first run if it can't find an `.apphub` file so most people won't need to create it manually.

However, based on your other Issue (#2) it looks like you're using this in an integration test so you'd want to create the `.apphub` file yourself.

I'll add a section with a sample .apphub file. 

Thanks for bringing this up!

**Comment by joshuapinter** [comment]
Thanks again for bringing this up @richardgill. 

I've added a section on the README with the sample format for the `.apphub` file.

In the future, I think allowing apphubdeploy to accept ENV variables that are passed in is the way to go. So, if `APPHUBID` or `APPHUBSECRET` is passed to the command it'll use those, otherwise, it'll first look for an existing `.apphub` file or finally prompt the user to enter in their credentials.
